Diplochain/apps/pagestud/urls.py
from django.urls import path
from .views import (
    nStudentDetailView,

)

urlpatterns = [
    path("<int:pk>", nStudentDetailView.as_view(), name="student-detail"),
    path("<int:pk>", nStudentDetailView.as_view(), name="student-detailstud"),
]

Diplochain/school_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path("admin",admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("apps.corecode.urls")),
    path("authentication/registration/login/pagestud/", include("apps.pagestud.urls")),
    path("pagestud/",include("apps.pagestud.urls")),
    path("authentication/registration/login/verification/",include("apps.verification.urls")),
    path("verification/", include("apps.verification.urls")),
    path("student/", include("apps.students.urls")),
    path("staff/", include("apps.staffs.urls")),
    path("result/", include("apps.result.urls")),
    path("authentication/", include("apps.authentication.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Diplochain/apps/staffs/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Staff(models.Model):
    GENDER = [("homme", "Homme"), ("femme", "Femme")]
    surname = models.CharField(max_length=200)
    firstname = models.CharField(max_length=200)
    identifiant=models.CharField(max_length=15,unique=True)
    gender = models.CharField(max_length=10, choices=GENDER, default="male")
    date_of_birth = models.DateField(default=timezone.now)
    current_status = models.CharField(max_length=30)
    mobile_num_regex = RegexValidator(
        regex="^[0-9]{10,15}$", message="Entered mobile number isn't in a right format!"
    )
    mobile_number = models.CharField(
        validators=[mobile_num_regex], max_length=13, blank=True
    )

    address = models.CharField(max_length=30,blank=True)
    others = models.TextField(blank=True)

    def __str__(self):
        return f"{self.surname} {self.firstname}"

    def get_absolute_url(self):
        return reverse("staff-detail", kwargs={"pk": self.pk})

Diplochain/apps/pagestud/views.py
import csv

from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic import DetailView

#from .models import pagestudent
from apps.students.models import Student

#
class nStudentDetailView(LoginRequiredMixin,DetailView):
    model = Student
    template_name = "student_detailstud.html"

    def get_context_data(self, **kwargs):
        context = super(nStudentDetailView, self).get_context_data(**kwargs)
        return context
       
 

Diplochain/apps/pagestud/templates/student_detailstud.html
{% extends 'base2.html' %}
{% load static %}

{% block content-header %}
<div class="card-header">
  <div class="card-tools">
    <a href="#" class="btn btn-tool"></a>
   
  </div>
</div>
{% endblock content-header %}

{% block content %}
    <div class="row mb-4">
      <div class="col-sm-4">
        <div class="row mb-2">

          {% if object.passport %}
            <img
              src="{{ object.passport.url }}"
              class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
          {% else %}
            <img
              src="{% static 'dist/img/avatar.png' %}"
              class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
          {% endif %}


          <div class="float-right">
            <h4>{{ object.surname }} </h4>
            <h4>{{ object.firstname }} </h4>
            <h4>{{ object.other_name }} </h4>
            <h4>{{ object.identifiant }} </h4>
          </div>
        </div>
        <h5>{{ object.current_class }} </h5>
        <h5>{{ object.get_gender_display }} | {{ object.get_current_status_display }}</h5>

      </div>
      <div class="col-sm-8">
        <div>
          <div class="form-group border-bottom row">
            <label class="col">
              Date de naissance
            </label>
            <div class="col">
              {{ object.date_of_birth }}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
              Numéro de téléphone
            </label>
            <div class="col">
              {{ object.mobile_number}}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
              Addresse
            </label>
            <div class="col">
              {{ object.address }}
            </div>
          </div>
          <div class="form-group border-bottom row">
            <label class="col">
              Comments
            </label>
            <div class="col">
              {{ object.others }}
            </div>
          </div>
          {% if object.diplom %}
            <a href="{{ object.diplom.url }}" download>Télécharger votre diplome ici</a>
          {% else %}
            <p>No file available for download.</p>
          {% endif %}
        </div>

      </div>
    </div>



{% endblock content %}